version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/go/src/github.com/CelesteComet/celeste-web-server
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=celeste-web-server' >> $BASH_ENV 
      - run:
          name: Run Tests
          command: |
            go test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t celeste-comet/$IMAGE_NAME:$TAG .
            docker push brucewong21/celeste-comet/$IMAGE_NAME:$TAG
       #     ssh -o StrictHostKeyChecking=no ec2-user@ec2-100-26-187-62.compute-1.amazonaws.com
      #- run:
          #name: Deploy app to Digital Ocean Server via Docker
          #command: |
          #  ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh ariv3ra/$IMAGE_NAME:$TAG"