version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    working_directory: ~/go/src/github.com/CelesteComet/celeste-web-server
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            echo 'export BUILD_NUM=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export TAG=latest' >> $BASH_ENV
            echo 'export IMAGE_NAME=celeste-web-server' >> $BASH_ENV 
            echo 'export DOCKER_NAME=brucewong21' >> $BASH_ENV
      - run:
          name: Run Tests
          command: |
            go test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build -t $IMAGE_NAME:$TAG .
            docker tag $IMAGE_NAME:$TAG brucewong21/$IMAGE_NAME:$TAG
            docker push brucewong21/$IMAGE_NAME:$TAG
            ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-84-145-40.compute-1.amazonaws.com "/bin/bash ./deploy_app.sh brucewong21/celeste-web-server:latest"
