version: 2
jobs:
  build:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: |
          echo Running Go Tests
          go test
          echo Go Test Complete
          go run main.go
