version: 2

jobs:
  test:
    docker:
      - image: circleci/golang
    steps:
      - checkout
      - run: |
          echo Running Go Tests\n
          go test
          echo Go Test Complete\n
  deploy:
    docker:
      - image: circleci/golang
    steps:
      - checkout

workflows:
  version: 2
  my_workflow:
    jobs:
      - test
      - deploy:
          requires:
            - test 

