version: 2

workflows:
  build-test-deploy:   
    jobs:
      - test:
          docker:
            - image: circleci/golang
          steps:
            - checkout
            - run: |
                echo Running Go Tests\n
                go test
                echo Go Test Complete\n
      - deploy:
          docker:
            - image: circleci/golang
          steps:
            - run: |
                go run main.go
